---
AllCops:
  TargetRubyVersion: 2.3

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/*

Style/Documentation:
  Enabled: false
